#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb  5 06:48:01 2024

@author: user
"""
import pandas as pd
df = pd.read_csv("movie_dataset.csv")
df.columns = df.columns.str.replace(' ', '_')

columns_with_nans = df.columns[df.isna().any()].tolist()
        
df['Metascore'].interpolate(method='linear', inplace=True)
         

mean_Revenue = df["Revenue_(Millions)"].mean()
df["Revenue_(Millions)"].fillna(mean_Revenue, inplace=True)
duplicate_rows = df[df.duplicated()]

movies_2016 = df[df["Year"] == 2016]
num_movies2016 = len(movies_2016)
print(num_movies2016)



