#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Feb  4 01:58:32 2024

@author: user
"""

import pandas as pd
df = pd.read_csv("movie_dataset.csv")
df.columns = df.columns.str.replace(' ', '_')

columns_with_nans = df.columns[df.isna().any()].tolist()
        
df['Metascore'].interpolate(method='linear', inplace=True)
         

mean_Revenue = df["Revenue_(Millions)"].mean()
print(mean_Revenue)









