#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb  5 08:28:02 2024

@author: user
"""

import pandas as pd
df = pd.read_csv("movie_dataset.csv")
df.columns = df.columns.str.replace(' ', '_')

columns_with_nans = df.columns[df.isna().any()].tolist()
        
df['Metascore'].interpolate(method='linear', inplace=True)
         

mean_Revenue = df["Revenue_(Millions)"].mean()
df["Revenue_(Millions)"].fillna(mean_Revenue, inplace=True)
duplicate_rows = df[df.duplicated()]

groupedmovies = df.groupby("Year")
avgrating = groupedmovies['Rating'].mean()

highest_rating_year = avgrating.idxmax() 
print(highest_rating_year)