#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb  5 08:41:32 2024

@author: user
"""
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("movie_dataset.csv")
df.columns = df.columns.str.replace(' ', '_')

columns_with_nans = df.columns[df.isna().any()].tolist()
        
df['Metascore'].interpolate(method='linear', inplace=True)
         

mean_Revenue = df["Revenue_(Millions)"].mean()
df["Revenue_(Millions)"].fillna(mean_Revenue, inplace=True)

df_numeric = df.select_dtypes(include = ["float", "int"])

df_numeric_correlation = df_numeric.corr()

print(df_numeric_correlation)   

#Heatmap
sns.heatmap(df_numeric_correlation, annot=True, cmap='coolwarm', fmt='.2f')

plt.title("Movies correlation heatmap")

plt.show()



